################################################################
author: Jaime_A_Castro_Mondragon

## === ##
## Bin ##
## === ##
bin : bin

python : python2.7
RSAT   : /lsc/rsat


## ============================================= ##
## Motif discovery (RSAT peak-motifs) parameters ##
## ============================================= ##
peakmotifs_disco : oligos,dyads,positions,local_words
peakmotifs_disco_nb_motifs : 2
peakmotifs_disco_min_oligo : 6
peakmotifs_disco_max_oligo : 7
peakmotifs_class_interval  : 25


central_pvalue : 0
top_motifs     : 3


## ==================================================== ##
## Homo sapiens hg38 : folders and required input files ##
## ==================================================== ##
data_folder       : /storage/mathelierarea/processed/jamondra/Projects/JASPAR/JASPAR_2022/Correct_number_sites/JASPAR_2022_motif_discovery_and_curation_pipeline/REMAP_2022_Hsapiens/data/hg38
TF_Experiment_map : /storage/mathelierarea/processed/rafael/JASPAR_2022_motif_discovery_and_curation_pipeline/REMAP_2022_Hsapiens/data/mapping.tsv
genome_fasta      : /storage/mathelierarea/raw/UCSC/hg38/Sequence/WholeGenomeFasta/genome.fa
genome_size       : /storage/mathelierarea/raw/UCSC/hg38/Sequence/WholeGenomeFasta/hg38_chrom_sizes
genome_name       : hg38
out_dir           : /storage/mathelierarea/processed/jamondra/Projects/JASPAR/JASPAR_2022/Correct_number_sites/JASPAR_2022_motif_discovery_and_curation_pipeline/REMAP_2022_Hsapiens/results
curation_dir      : /storage/mathelierarea/processed/jamondra/Projects/JASPAR/JASPAR_2022/Correct_number_sites/JASPAR_2022_motif_discovery_and_curation_pipeline/REMAP_2022_Hsapiens/results/curation
taxon             : Vertebrates
