################################################################
author: Jaime_A_Castro_Mondragon + Rafael_Ruidavets_Puig

## === ##
## Bin ##
## === ##
bin : /storage/scratch/JASPAR_2022/bin

python : python2.7
RSAT : /lsc/rsat


## ============================================= ##
## Motif discovery (RSAT peak-motifs) parameters ##
## ============================================= ##
peakmotifs_disco : oligos,dyads,positions,local_words
peakmotifs_disco_nb_motifs : 2
peakmotifs_disco_min_oligo : 6
peakmotifs_disco_max_oligo : 7
peakmotifs_class_interval : 25


central_pvalue : -50
top_motifs     : 3



## ================================================================= ##
## Arabaidposis thaliana (TAIR10) : folders and required input files ##
## ================================================================= ##
data_folder       : /storage/scratch/JASPAR_2022/REMAP_2020_Athaliana/data
TF_Experiment_map : /storage/scratch/JASPAR_2022/REMAP_2020_Athaliana/data/mapping.tsv
genome_fasta      : /storage/mathelierarea/raw/UCSC/TAIR10/Sequence/WholeGenomeFasta/TAIR10.fa
genome_size       : /storage/mathelierarea/raw/UCSC/TAIR10/Sequence/WholeGenomeFasta/TAIR10.chrom.sizes
genome_name       : TAIR10
out_dir           : /storage/scratch/JASPAR_2022/REMAP_2020_Athaliana/results
curation_dir      : /storage/scratch/JASPAR_2022/REMAP_2020_Athaliana/data/results/curation
taxon             : Plants
