################################################################
author: Jaime_A_Castro_Mondragon

## === ##
## Bin ##
## === ##
bin : /storage/scratch/JASPAR_2022/bin

python : python2.7
RSAT : /lsc/rsat


## ============================================= ##
## Motif discovery (RSAT peak-motifs) parameters ##
## ============================================= ##
peakmotifs_disco : oligos,dyads,positions,local_words
peakmotifs_disco_nb_motifs : 2
peakmotifs_disco_min_oligo : 6
peakmotifs_disco_max_oligo : 7
peakmotifs_class_interval : 25


central_pvalue : -200


## ==================================================== ##
## Homo sapiens hg38 : folders and required input files ##
## ==================================================== ##
data_folder : /storage/scratch/JASPAR_2022/ChExMix_sacCer3/data/Yeast_SacCer3
TF_Experiment_map : /storage/scratch/JASPAR_2022/ChExMix_sacCer3/data/Yeast_SacCer3/ChExMix_SacCer3_TF_exp_ID.txt
genome_fasta : /storage/scratch/JASPAR_2022/Genome_files/Yeast/sacCer3/sacCer3.fa
genome_size : /storage/scratch/JASPAR_2022/Genome_files/Yeast/sacCer3/sacCer3.chrom.sizes
out_dir : /storage/scratch/JASPAR_2022/ChExMix_sacCer3/results/Yeast_SacCer3
curation_dir :/storage/scratch/JASPAR_2022/ChExMix_sacCer3/results/Yeast_SacCer3/curation